### ISSUE TITLE
listen to touch event to trigger getSelectedText

### ISSUE THREAD

**Issue by balmas** [alpheios-project/pwa-prototype#13]
on the iOS the double-click event is not registering for finger touches. Can we add a touch event listener to trigger the getSelectedText method? I think we might want touchend rather than touchstart, I'm not sure.

**Comment by kirlat** [comment]
Yes, I think we can use touch events there.

**Comment by kirlat** [comment]
It seems that right now HTMLSelector is too tightly coupled with a MouseEvent event type. It cannot be used for touch events it its current state. I'm working on modifying it to make it more generic and being able to work with UIEvent children (i.e. MouseEvent, PointerEvent, TouchEvent). This might rise some issues of its own (how to determine a word boundary and how to get its context), so I'm thinking maybe it's better to create a separate issue for those HTMLSelector changes. What do you think?

**Comment by balmas** [comment]
Yes I agree.  Maybe we need to delegate to a class that is responsible for event-type-specific logic?

**Comment by kirlat** [comment]
Completed updates that should select a word with a touch. Please test it when you will have time. Thanks!

**Comment by balmas** [comment]
it's working :-)
