### ISSUE TITLE
Component issues to be fixed before feedback release

### ISSUE THREAD

**Issue by balmas** [alpheios-project/pwa-prototype#22]
- [x] iOS pointer issue (https://github.com/alpheios-project/components/issues/103)
- [x] cherry-pick treebank diagram fix from https://github.com/alpheios-project/components/commit/053c2cfff8a28a1014c3e8e705b4135dafcd442f#diff-32bccd16b255edb0601d7f294ddd0d5a (hide diagram panel if no diagram)
- [x] cherry-pick updated messages https://github.com/alpheios-project/components/pull/104

**Comment by kirlat** [comment]
alpheios-project/components#103 should be fixed by 4b6efeedc8f6b48653a38e5daf099313ce85fb54 (build 32). alpheios-project/components#104 should be fixed by 61615ede9e2d75a4777601cfd155610cad48b777 (build 33).

**Comment by balmas** [comment]
adding one more: 
- [ ] https://github.com/alpheios-project/components/issues/17

**Comment by balmas** [comment]
and 
[ ] updated grammar and inflection icons https://github.com/alpheios-project/components/pull/106

**Comment by balmas** [comment]
cherry-picked new icons into selection-test branch of components.
