### ISSUE TITLE
content page wants to load manifest from same directory

### ISSUE THREAD

**Issue by balmas** [alpheios-project/pwa-prototype#23]
The Gallic War page doesn't seem to have the pointer event activated on it, or if it does it's failing for some reason. Double-click works in the browser on the desktop but no response to touches on this page on my the Galaxy 7.  It does look like touch events are being activated on iOS (but they are failing presumably due to https://github.com/alpheios-project/components/issues/103)

**Comment by balmas** [comment]
renamed this issue because I think maybe there is a more general problem loading the child page on android. I also don't get the Back to TOC button there.

**Comment by balmas** [comment]
ok renamed this issue again :-) after debugging it seems that the problem might be that the page is trying to load the manifest from the same directory (i.e. content) rather than the parent directory.

**Comment by kirlat** [comment]
Please check how it works now, with static injection on content pages (builds 32 and up).

**Comment by balmas** [comment]
works well on my Galaxy 7. Testing iOs now...

**Comment by balmas** [comment]
iOs is working too. yay!
