### ISSUE TITLE
back to toc button not working consistently

### ISSUE THREAD

**Issue by balmas** [alpheios-project/pwa-prototype#30]
works okay in the browser (chrome) but haven't seen it working on my Galaxy 7 yet

**Comment by kirlat** [comment]
Replaced dynamic injection with static one in 4b6efeedc8f6b48653a38e5daf099313ce85fb54 (build 32). This should fix the issue in the short term. Will do more research and testing to determine if dynamic injection can be made more reliable in the long term.
