### ISSUE TITLE
let's rename the prototype 

### ISSUE THREAD

**Issue by balmas** [alpheios-project/pwa-prototype#34]
I think PWA is probably meaningless to most people.
@kirlat what do you think of Alpheios Mobile Reader Prototype (and maybe just Alpheios Reader as the short name)?

**Comment by kirlat** [comment]
I like this name, especially Alpheios Reader. I think it's short and reflect the purpose well.

**Comment by balmas** [comment]
ok, thanks! Please go ahead and make the change then :-)
