### ISSUE TITLE
show as many icons as possible before showing menu

### ISSUE THREAD

**Issue by balmas** [alpheios-project/pwa-prototype#49]
@abrasax requests that we still show icons on the panel bar even if they don't all fit, collapsing into the menu only the icons we didn't have room for

Perhaps for now we could always show morphology, definitions and inflections, and collapse the rest under the menu if there isn't room for them?

Longer term, we could think about allowing the user to specific which functions are most important to make accessible at a single finger/key stroke.

**Comment by kirlat** [comment]
Should be fixed with b7a25ac59ae944840074550d23a3d33773cfec03, please verify if it's working the way it should.

**Comment by balmas** [comment]
this looks good to me.
