### ISSUE TITLE
add pwa manifest version to interface

### ISSUE THREAD

**Issue by balmas** [alpheios-project/pwa-prototype#9]
we should version the pwa manifest and add that to the ui in the info panel so that we can be sure we know which version we are looking at.

**Comment by kirlat** [comment]
I think it is a great idea.

**Comment by kirlat** [comment]
PWA manifest is generated during build, so we cannot use it as a source of data. Config data for generating a manifest is in `build/config.mjs`, but I think putting an app meta data there would not be a good idea as it is just a build script config file and nothing more. Also, specs do not define a `version` field in a PWA manifest; the only place from where we could take a version number is a `package.json` file.

So I decided that a `package.json` would be a natural place to put an application meta. It is already used to describe an application, so it would be natural to use `package.json` as a single source of truth of our app config. npm does not prohibit us from having properties there that do not conflict with ones specified in `package.json` specs.

So I created an `alpheios` property there, under which we could store all our app specific config data:
```
"alpheios": {
    "pwa": {
      "name": "Alpheios PWA",
      "short_name": "Alpheios PWA",
      "lang": "en-US",
      "display": "standalone",
      "theme_color": "#73CDDE",
      "background_color": "#333333"
    }
  }
```
`alpheios` property name would most likely to be unique. It also makes clear who is a consumer of this data.

Both `config.mjs` and an app JS files read information from `package.json` and use it to generate a PWA manifest and to display an app info in the "info" panel.

Please let me know what do you think about this design.

**Comment by balmas** [comment]
this seems fine to me!
